name: prom-node-exporter
version: 0.1
synthesizer:
  freqUpper: 450
  freqLower: 200
metronome:
  bpmMin: 0
  bpmMax: 300
prometheus:
  port: 9090
  scheme: http
  url: 0.0.0.0
audioQueries:
  - name: cpuUsage
    query: rate(process_cpu_seconds_total{job="node-exporter"}[1m])
    type: SYNTH
    # Default min/max are 0/1 which works well for percentage results
  - name: memoryUsage
    query: 1 - (node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes)
    type: SYNTH
  - name: diskUsage
    query: 1 - ( node_filesystem_avail_bytes{mountpoint="/",fstype!="rootfs"} / node_filesystem_size_bytes{mountpoint="/",fstype!="rootfs"} )
    type: METRO
    min: 0
    max: 1
